<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-13T14:51:33 IST" name="Suite" finished-at="2025-10-13T14:51:42 IST" duration-ms="8638">
    <groups>
    </groups>
    <test started-at="2025-10-13T14:51:33 IST" name="Test" finished-at="2025-10-13T14:51:42 IST" duration-ms="8638">
      <class name="api.testcases.UserTest">
        <test-method is-config="true" signature="generateTestData()[pri:0, instance:api.testcases.UserTest@10e41621]" started-at="2025-10-13T14:51:33 IST" name="generateTestData" finished-at="2025-10-13T14:51:34 IST" duration-ms="458" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateTestData -->
        <test-method signature="testcreateUser()[pri:1, instance:api.testcases.UserTest@10e41621]" started-at="2025-10-13T14:51:34 IST" name="testcreateUser" finished-at="2025-10-13T14:51:36 IST" duration-ms="2466" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcreateUser -->
        <test-method signature="testgetUserData()[pri:2, instance:api.testcases.UserTest@10e41621]" started-at="2025-10-13T14:51:36 IST" name="testgetUserData" finished-at="2025-10-13T14:51:37 IST" duration-ms="1167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testgetUserData -->
        <test-method signature="testupdateUserData()[pri:3, instance:api.testcases.UserTest@10e41621]" started-at="2025-10-13T14:51:37 IST" name="testupdateUserData" finished-at="2025-10-13T14:51:39 IST" duration-ms="2236" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testupdateUserData -->
        <test-method signature="testdeleteUserData()[pri:4, instance:api.testcases.UserTest@10e41621]" started-at="2025-10-13T14:51:39 IST" name="testdeleteUserData" finished-at="2025-10-13T14:51:42 IST" duration-ms="2127" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at org.testng.Assert.assertEquals(Assert.java:1441)
at api.testcases.UserTest.testdeleteUserData(UserTest.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testdeleteUserData -->
      </class> <!-- api.testcases.UserTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
